<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<OutputPath>..\Assemblies\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Optimize>true</Optimize>
		<DebugType>portable</DebugType>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4535" />
		<PackageReference Include="Lib.Harmony" Version="2.3.2">
			<ExcludeAssets>runtime</ExcludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<Reference Include="CombatExtended">
			<HintPath>C:\Steam\steamapps\workshop\content\294100\3495749827\Assemblies\CombatExtended.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>